### ISSUE TITLE
numpy 1.x vs numpy 2.x issue with dependency blosc2

### ISSUE THREAD

**Issue by snorthman** [MIC-DKFZ/nnUNet#2913]
```
Traceback (most recent call last):
  File "/usr/local/bin/nnUNetv2_find_best_configuration", line 3, in <module>
    from nnunetv2.evaluation.find_best_configuration import find_best_configuration_entry_point
  File "/root/nnunet/nnunetv2/evaluation/find_best_configuration.py", line 10, in <module>
    from nnunetv2.ensembling.ensemble import ensemble_crossvalidations
  File "/root/nnunet/nnunetv2/ensembling/ensemble.py", line 13, in <module>
    from nnunetv2.utilities.label_handling.label_handling import LabelManager
  File "/root/nnunet/nnunetv2/utilities/label_handling/label_handling.py", line 7, in <module>
    from acvl_utils.cropping_and_padding.bounding_boxes import bounding_box_to_slice, insert_crop_into_image
  File "/usr/local/lib/python3.11/site-packages/acvl_utils/cropping_and_padding/bounding_boxes.py", line 5, in <module>
    import blosc2
  File "/usr/local/lib/python3.11/site-packages/blosc2/__init__.py", line 174, in <module>
    isdtype = np.isdtype
              ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/numpy/__init__.py", line 333, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'isdtype'. Did you mean: 'dtype'?
```

`isdtype` is a numpy 2.x function. nnunetv2 dependencies are `"numpy>=1.24"` and `"blosc2>=3.0.0b1"`. Today, `blosc2` requires `"numpy>=2.1"`.

Will nnunetv2 work with `"numpy>=2.1"`?

**Comment by snorthman** [comment]
I'm surprised if you have this issue. I closed it without explanation because my logic was wrong. If `blosc2>=3.0.0b1` and `numpy>=1.24`, then `pip` resolves this with installing `numpy>=2.1`. 

Anyways, the problem was that my environment was broken, and it wouldn't install a newer version of `numpy` for that reason.
